#!/bin/bash

#if ping -c 1 -W 1 $1 > /dev/null; then
#echo "q"
#else
#echo "f"
#fi
nslookup $1 -timeout=1 > /dev/null
case $? in
	0) echo $2'${alignr}${font}${color green}'$1'${font StyleBats:size=10} q${color}${font}   ' ;;
	1) echo '${font}${color yellow}'$1'${font StyleBats:size=10} f${color}${font}' ;;
esac
#case $? in
#	0) echo '${alignr}${font}${color green}'$1' ::${font StyleBats:size=10} q${color}${font}' ;;
#	1) echo '${font}${color yellow}'$1' ::${font StyleBats:size=10} f${color}${font}' ;;
#	2) echo "f" ;;
#esac
