#!/bin/bash

#if ping -c 1 -W 1 $1 > /dev/null; then
#echo "q"
#else
#echo "f"
#fi
ping -c 1 -W 1 $1 > /dev/null
case $? in
	0) export PINGHOST=`nslookup -class=IN -timeout=1 $1 | grep -m 2 Address | grep -v 127.0 | grep -v '10.0.0.10#' | cut -c 10-`
	   echo '${voffset -1}${font}${color light green}'$1'${alignr}'$PINGHOST'${color}${font}         ' ;;
	1) export PINGHOST=`nslookup -class=IN -timeout=1 $1 | grep -m 2 Address | grep -v 127.0 | grep -v '10.0.0.10#' | cut -c 10-`
	   echo '${voffset -1}${font}${color orange}'$1'${alignr}'$PINGHOST'${color}${font}         ' ;;
	2) echo '${voffset -1}${font}${color FF440}'$1'${alignr}${blink DNS Error}${color}${font}' ;;
esac


#if nslookup -class=IN -timeout=1 $1 > /dev/null; then
#	export PINGHOST=`nslookup -class=IN -timeout=1 $1 | grep -m 2 Address | grep -v 127.0 | grep -v '10.0.0.10#' | cut -c 10-`
#	ping -c 1 -W 1 $PINGHOST > /dev/null
#	case $? in
#		0) echo '${voffset -1}${font}${color light green}'$1'${alignr}'$PINGHOST'${color}${font}         ' ;;
#		1) echo '${voffset -1}${font}${color orange}'$1'${alignr}'$PINGHOST'${color}${font}         ' ;;
#	esac
#else
#	echo '${voffset -1}${font}${color FF4400}'$1'${alignr}${blink DNS Error}${color}${font}         ' 
#fi
