#!/bin/bash

ping -c 1 -W 1 $1 > /dev/null
case $? in
	0) echo '${voffset -1}${font}${color light green}'$2'${alignr}'$1'${font StyleBats:size=10} q${color}${font}          ' ;;
	1) echo '${voffset -1}${font}${color orange}'$2'${alignr}'$1'${font StyleBats:size=10} f${color}${font}          ' ;;
esac
