#!/bin/bash
nmap $1 -p $2 | grep open > /dev/null
case $? in
	0) echo '${voffset -1}${goto 15}${color light green}   '$3' ${goto 130}'$2'${color}' ;;
	1) echo '${voffset -1}${goto 15}${color orange}   '$3' ${goto 130}'$2'${color}' ;;
esac
